### ISSUE TITLE
Rendering: Recursive list/map trait causes StackOverflowError

### ISSUE THREAD

**Issue by kubukoz** [disneystreaming/smithy4s#1308]
Case A, lists:

```smithy
$version: "2"

namespace test

@trait
list Foo {
    @Foo
    member: String
}
```

<details><summary>Stack trace</summary>

```
java.lang.StackOverflowError
	at smithy4s.codegen.internals.SmithyToIR$$anon$2.$anonfun$getExternalTypeInfo$1(SmithyToIR.scala:508)
	at scala.collection.StrictOptimizedMapOps.flatMap(StrictOptimizedMapOps.scala:31)
	at scala.collection.StrictOptimizedMapOps.flatMap$(StrictOptimizedMapOps.scala:30)
	at scala.collection.convert.JavaCollectionWrappers$AbstractJMapWrapper.flatMap(JavaCollectionWrappers.scala:344)
	at smithy4s.codegen.internals.SmithyToIR$$anon$2.getExternalTypeInfo(SmithyToIR.scala:506)
	at smithy4s.codegen.internals.SmithyToIR$$anon$2.getExternalOrBase(SmithyToIR.scala:531)
	at smithy4s.codegen.internals.SmithyToIR$$anon$2.primitive(SmithyToIR.scala:574)
	at smithy4s.codegen.internals.SmithyToIR$$anon$2.stringShape(SmithyToIR.scala:742)
	at smithy4s.codegen.internals.SmithyToIR$$anon$2.stringShape(SmithyToIR.scala:476)
	at software.amazon.smithy.model.shapes.StringShape.accept(StringShape.java:41)
	at smithy4s.codegen.internals.SmithyToIR$ShapeIdExt.$anonfun$tpe$1(SmithyToIR.scala:1113)
	at scala.Option.flatMap(Option.scala:283)
	at smithy4s.codegen.internals.SmithyToIR$ShapeIdExt.tpe(SmithyToIR.scala:1113)
	at smithy4s.codegen.internals.SmithyToIR.smithy4s$codegen$internals$SmithyToIR$$unfoldTrait(SmithyToIR.scala:1176)
	at smithy4s.codegen.internals.SmithyToIR.$anonfun$hints$5(SmithyToIR.scala:968)
	at scala.collection.immutable.List.map(List.scala:246)
	at smithy4s.codegen.internals.SmithyToIR.smithy4s$codegen$internals$SmithyToIR$$hints(SmithyToIR.scala:968)
	at smithy4s.codegen.internals.SmithyToIR$ShapeExt.$anonfun$fields$2(SmithyToIR.scala:1001)
	at scala.collection.StrictOptimizedIterableOps.map(StrictOptimizedIterableOps.scala:100)
	at scala.collection.StrictOptimizedIterableOps.map$(StrictOptimizedIterableOps.scala:87)
	at scala.collection.mutable.ArrayBuffer.map(ArrayBuffer.scala:43)
	at smithy4s.codegen.internals.SmithyToIR$ShapeExt.fields(SmithyToIR.scala:990)
	at smithy4s.codegen.internals.SmithyToIR.unfoldNodeAndType(SmithyToIR.scala:1187)
	at smithy4s.codegen.internals.SmithyToIR.$anonfun$unfoldTrait$1(SmithyToIR.scala:1177)
	at smithy4s.codegen.internals.recursion$.hylo(recursion.scala:41)
	at smithy4s.codegen.internals.recursion$.ana(recursion.scala:63)
	at smithy4s.codegen.internals.SmithyToIR.smithy4s$codegen$internals$SmithyToIR$$unfoldTrait(SmithyToIR.scala:1177)
	at smithy4s.codegen.internals.SmithyToIR$$anonfun$traitToHint$1.applyOrElse(SmithyToIR.scala:904)
	at smithy4s.codegen.internals.SmithyToIR$$anonfun$traitToHint$1.applyOrElse(SmithyToIR.scala:876)
	at scala.collection.immutable.List.collect(List.scala:267)
	at smithy4s.codegen.internals.SmithyToIR.smithy4s$codegen$internals$SmithyToIR$$hints(SmithyToIR.scala:964)
	at smithy4s.codegen.internals.SmithyToIR$$anon$2.$anonfun$listShape$2(SmithyToIR.scala:624)
	at scala.Option.map(Option.scala:242)
	at smithy4s.codegen.internals.SmithyToIR$$anon$2.listShape(SmithyToIR.scala:623)
	at smithy4s.codegen.internals.SmithyToIR$$anon$2.listShape(SmithyToIR.scala:476)
	at software.amazon.smithy.model.shapes.ListShape.accept(ListShape.java:42)
	at smithy4s.codegen.internals.SmithyToIR$$anon$2.$anonfun$memberShape$1(SmithyToIR.scala:761)
	at scala.Option.flatMap(Option.scala:283)
	at smithy4s.codegen.internals.SmithyToIR$$anon$2.memberShape(SmithyToIR.scala:754)
	at smithy4s.codegen.internals.SmithyToIR$$anon$2.memberShape(SmithyToIR.scala:476)
	at software.amazon.smithy.model.shapes.MemberShape.accept(MemberShape.java:60)
	at smithy4s.codegen.internals.SmithyToIR$ShapeExt.tpe(SmithyToIR.scala:979)
	at smithy4s.codegen.internals.SmithyToIR$ShapeExt.$anonfun$fields$2(SmithyToIR.scala:999)
	at scala.collection.StrictOptimizedIterableOps.map(StrictOptimizedIterableOps.scala:100)
	at scala.collection.StrictOptimizedIterableOps.map$(StrictOptimizedIterableOps.scala:87)
...
```

</details> 

Case B, maps:

```smithy
$version: "2"

namespace test

@trait
map Foo {
    @Foo
    key: String
    value: String
}
```

<details><summary>Stack trace</summary>

```
java.lang.StackOverflowError
	at software.amazon.smithy.model.shapes.Shape.shapeToBuilder(Shape.java:219)
	at smithy4s.codegen.internals.SmithyToIR$$anon$2.$anonfun$memberShape$1(SmithyToIR.scala:756)
	at scala.Option.flatMap(Option.scala:283)
	at smithy4s.codegen.internals.SmithyToIR$$anon$2.memberShape(SmithyToIR.scala:754)
	at smithy4s.codegen.internals.SmithyToIR$$anon$2.memberShape(SmithyToIR.scala:476)
	at software.amazon.smithy.model.shapes.MemberShape.accept(MemberShape.java:60)
	at smithy4s.codegen.internals.SmithyToIR$$anon$2.mapShape(SmithyToIR.scala:672)
	at smithy4s.codegen.internals.SmithyToIR$$anon$2.mapShape(SmithyToIR.scala:476)
	at software.amazon.smithy.model.shapes.MapShape.accept(MapShape.java:63)
	at smithy4s.codegen.internals.SmithyToIR$ShapeIdExt.$anonfun$tpe$1(SmithyToIR.scala:1113)
	at scala.Option.flatMap(Option.scala:283)
	at smithy4s.codegen.internals.SmithyToIR$ShapeIdExt.tpe(SmithyToIR.scala:1113)
	at smithy4s.codegen.internals.SmithyToIR.smithy4s$codegen$internals$SmithyToIR$$unfoldTrait(SmithyToIR.scala:1176)
	at smithy4s.codegen.internals.SmithyToIR.$anonfun$hints$5(SmithyToIR.scala:968)
	at scala.collection.immutable.List.map(List.scala:246)
	at smithy4s.codegen.internals.SmithyToIR.smithy4s$codegen$internals$SmithyToIR$$hints(SmithyToIR.scala:968)
	at smithy4s.codegen.internals.SmithyToIR$$anon$2.getHints(SmithyToIR.scala:608)
	at smithy4s.codegen.internals.SmithyToIR$$anon$2.$anonfun$mapShape$3(SmithyToIR.scala:678)
	at scala.Option.map(Option.scala:242)
	at smithy4s.codegen.internals.SmithyToIR$$anon$2.$anonfun$mapShape$1(SmithyToIR.scala:673)
	at scala.Option.flatMap(Option.scala:283)
	at smithy4s.codegen.internals.SmithyToIR$$anon$2.mapShape(SmithyToIR.scala:672)
	at smithy4s.codegen.internals.SmithyToIR$$anon$2.mapShape(SmithyToIR.scala:476)
	at software.amazon.smithy.model.shapes.MapShape.accept(MapShape.java:63)
	at smithy4s.codegen.internals.SmithyToIR$ShapeIdExt.$anonfun$tpe$1(SmithyToIR.scala:1113)
	at scala.Option.flatMap(Option.scala:283)
	at smithy4s.codegen.internals.SmithyToIR$ShapeIdExt.tpe(SmithyToIR.scala:1113)
	at smithy4s.codegen.internals.SmithyToIR.smithy4s$codegen$internals$SmithyToIR$$unfoldTrait(SmithyToIR.scala:1176)
	at smithy4s.codegen.internals.SmithyToIR.$anonfun$hints$5(SmithyToIR.scala:968)
	at scala.collection.immutable.List.map(List.scala:246)
	at smithy4s.codegen.internals.SmithyToIR.smithy4s$codegen$internals$SmithyToIR$$hints(SmithyToIR.scala:968)
	at smithy4s.codegen.internals.SmithyToIR$$anon$2.getHints(SmithyToIR.scala:608)
	at smithy4s.codegen.internals.SmithyToIR$$anon$2.$anonfun$mapShape$3(SmithyToIR.scala:678)
	at scala.Option.map(Option.scala:242)
	at smithy4s.codegen.internals.SmithyToIR$$anon$2.$anonfun$mapShape$1(SmithyToIR.scala:673)
	at scala.Option.flatMap(Option.scala:283)
	at smithy4s.codegen.internals.SmithyToIR$$anon$2.mapShape(SmithyToIR.scala:672)
	at smithy4s.codegen.internals.SmithyToIR$$anon$2.mapShape(SmithyToIR.scala:476)
	at software.amazon.smithy.model.shapes.MapShape.accept(MapShape.java:63)
	at smithy4s.codegen.internals.SmithyToIR$ShapeIdExt.$anonfun$tpe$1(SmithyToIR.scala:1113)
	at scala.Option.flatMap(Option.scala:283)
	at smithy4s.codegen.internals.SmithyToIR$ShapeIdExt.tpe(SmithyToIR.scala:1113)
	at smithy4s.codegen.internals.SmithyToIR.smithy4s$codegen$internals$SmithyToIR$$unfoldTrait(SmithyToIR.scala:1176)
	at smithy4s.codegen.internals.SmithyToIR.$anonfun$hints$5(SmithyToIR.scala:968)
	at scala.collection.immutable.List.map(List.scala:246)
	at smithy4s.codegen.internals.SmithyToIR.smithy4s$codegen$internals$SmithyToIR$$hints(SmithyToIR.scala:968)
	at smithy4s.codegen.internals.SmithyToIR$$anon$2.getHints(SmithyToIR.scala:608)
	at smithy4s.codegen.internals.SmithyToIR$$anon$2.$anonfun$mapShape$3(SmithyToIR.scala:678)
```

</details> 

This is a separate issue from #1296 because `ana` isn't involved: this seems to be happening strictly due to unbounded recursion in `unfoldTrait` + `hints`.

**Comment by kubukoz** [comment]
This is still a thing in 0.18.33
