### ISSUE TITLE
IllegalStateException in json decoding

### ISSUE THREAD

**Issue by kubukoz** [disneystreaming/smithy4s#222]
Given this schema:

```
namespace jsonschema

use smithy4s.api#discriminated
use smithy4s.api#untagged

service SynthService { operations: [SynthOp] }
operation SynthOp { input: Schema }

structure Schema {
  definitions: Definitions,
  properties: Properties,
  required: Strings,
  type: SchemaType,
  @jsonName("$ref")
  ref: Ref
}

string Ref

list Strings { member: String }

map Definitions {
  key: DefinitionName,
  value: Document //todo
}

// synthetic
string DefinitionName


@untagged
union SchemaType {
  simple: SimpleType,
  simpleArray: SimpleTypeArray,
  array: SchemaArray,
  anyOf: SchemaArray
}

// structure

@length(min: 1)
list SimpleTypeArray {
  member: SimpleType
}

@length(min: 1)
list SchemaArray {
  member: Schema
}

map Properties {
  key: PropName,
  value: Property
}

@untagged
union Property {
  schema: Schema,
  // In the case of `default`.
  // now I really wish we had mixins
  bool: Boolean
}

string PropName

@enum([
  {value: "boolean", name: "BOOLEAN"},
  {value: "integer", name: "INTEGER"},
  {value: "null", name: "NULL"},
  {value: "number", name: "NUMBER"},
  {value: "object", name: "OBJECT"},
  {value: "string", name: "STRING"},
])
string SimpleType
```

and the JSON Schema spec:

```json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "definitions": {
    "AndType": {
      "additionalProperties": false,
      "description": "Represents an `and`type (e.g. TextDocumentParams & WorkDoneProgressParams`).",
      "properties": {
        "items": {
          "items": {
            "$ref": "#/definitions/Type"
          },
          "type": "array"
        },
        "kind": {
          "const": "and",
          "type": "string"
        }
      },
      "required": ["kind", "items"],
      "type": "object"
    },
    "ArrayType": {
      "additionalProperties": false,
      "description": "Represents an array type (e.g. `TextDocument[]`).",
      "properties": {
        "element": {
          "$ref": "#/definitions/Type"
        },
        "kind": {
          "const": "array",
          "type": "string"
        }
      },
      "required": ["kind", "element"],
      "type": "object"
    },
    "BaseType": {
      "additionalProperties": false,
      "description": "Represents a base type like `string` or `DocumentUri`.",
      "properties": {
        "kind": {
          "const": "base",
          "type": "string"
        },
        "name": {
          "$ref": "#/definitions/BaseTypes"
        }
      },
      "required": ["kind", "name"],
      "type": "object"
    },
    "BaseTypes": {
      "enum": [
        "Uri",
        "DocumentUri",
        "integer",
        "uinteger",
        "decimal",
        "RegExp",
        "string",
        "boolean",
        "null"
      ],
      "type": "string"
    },
    "BooleanLiteralType": {
      "additionalProperties": false,
      "description": "Represents a boolean literal type (e.g. `kind: true`).",
      "properties": {
        "kind": {
          "const": "booleanLiteral",
          "type": "string"
        },
        "value": {
          "type": "boolean"
        }
      },
      "required": ["kind", "value"],
      "type": "object"
    },
    "Enumeration": {
      "additionalProperties": false,
      "description": "Defines an enumeration.",
      "properties": {
        "documentation": {
          "description": "An optional documentation.",
          "type": "string"
        },
        "name": {
          "description": "The name of the enumeration.",
          "type": "string"
        },
        "proposed": {
          "description": "Whether this is a proposed enumeration. If omitted, the enumeration is final.",
          "type": "boolean"
        },
        "since": {
          "description": "Since when (release number) this enumeration is available. Is undefined if not known.",
          "type": "string"
        },
        "supportsCustomValues": {
          "description": "Whether the enumeration supports custom values (e.g. values which are not part of the set defined in `values`). If omitted no custom values are supported.",
          "type": "boolean"
        },
        "type": {
          "$ref": "#/definitions/EnumerationType",
          "description": "The type of the elements."
        },
        "values": {
          "description": "The enum values.",
          "items": {
            "$ref": "#/definitions/EnumerationEntry"
          },
          "type": "array"
        }
      },
      "required": ["name", "type", "values"],
      "type": "object"
    },
    "EnumerationEntry": {
      "additionalProperties": false,
      "description": "Defines an enumeration entry.",
      "properties": {
        "documentation": {
          "description": "An optional documentation.",
          "type": "string"
        },
        "name": {
          "description": "The name of the enum item.",
          "type": "string"
        },
        "proposed": {
          "description": "Whether this is a proposed enumeration entry. If omitted, the enumeration entry is final.",
          "type": "boolean"
        },
        "since": {
          "description": "Since when (release number) this enumeration entry is available. Is undefined if not known.",
          "type": "string"
        },
        "value": {
          "description": "The value.",
          "type": ["string", "number"]
        }
      },
      "required": ["name", "value"],
      "type": "object"
    },
    "EnumerationType": {
      "additionalProperties": false,
      "properties": {
        "kind": {
          "const": "base",
          "type": "string"
        },
        "name": {
          "enum": ["string", "integer"],
          "type": "string"
        }
      },
      "required": ["kind", "name"],
      "type": "object"
    },
    "IntegerLiteralType": {
      "additionalProperties": false,
      "properties": {
        "kind": {
          "const": "integerLiteral",
          "description": "Represents an integer literal type (e.g. `kind: 1`).",
          "type": "string"
        },
        "value": {
          "type": "number"
        }
      },
      "required": ["kind", "value"],
      "type": "object"
    },
    "MapKeyType": {
      "anyOf": [
        {
          "additionalProperties": false,
          "properties": {
            "kind": {
              "const": "base",
              "type": "string"
            },
            "name": {
              "enum": ["Uri", "DocumentUri", "string", "integer"],
              "type": "string"
            }
          },
          "required": ["kind", "name"],
          "type": "object"
        },
        {
          "$ref": "#/definitions/ReferenceType"
        }
      ],
      "description": "Represents a type that can be used as a key in a map type. If a reference type is used then the type must either resolve to a `string` or `integer` type. (e.g. `type ChangeAnnotationIdentifier === string`)."
    },
    "MapType": {
      "additionalProperties": false,
      "description": "Represents a JSON object map (e.g. `interface Map<K extends string | integer, V> { [key: K] => V; }`).",
      "properties": {
        "key": {
          "$ref": "#/definitions/MapKeyType"
        },
        "kind": {
          "const": "map",
          "type": "string"
        },
        "value": {
          "$ref": "#/definitions/Type"
        }
      },
      "required": ["kind", "key", "value"],
      "type": "object"
    },
    "MetaModel": {
      "additionalProperties": false,
      "description": "The actual meta model.",
      "properties": {
        "enumerations": {
          "description": "The enumerations.",
          "items": {
            "$ref": "#/definitions/Enumeration"
          },
          "type": "array"
        },
        "notifications": {
          "description": "The notifications.",
          "items": {
            "$ref": "#/definitions/Notification"
          },
          "type": "array"
        },
        "requests": {
          "description": "The requests.",
          "items": {
            "$ref": "#/definitions/Request"
          },
          "type": "array"
        },
        "structures": {
          "description": "The structures.",
          "items": {
            "$ref": "#/definitions/Structure"
          },
          "type": "array"
        },
        "typeAliases": {
          "description": "The type aliases.",
          "items": {
            "$ref": "#/definitions/TypeAlias"
          },
          "type": "array"
        }
      },
      "required": [
        "requests",
        "notifications",
        "structures",
        "enumerations",
        "typeAliases"
      ],
      "type": "object"
    },
    "Notification": {
      "additionalProperties": false,
      "description": "Represents a LSP notification",
      "properties": {
        "documentation": {
          "description": "An optional documentation;",
          "type": "string"
        },
        "method": {
          "description": "The request's method name.",
          "type": "string"
        },
        "params": {
          "anyOf": [
            {
              "$ref": "#/definitions/Type"
            },
            {
              "items": {
                "$ref": "#/definitions/Type"
              },
              "type": "array"
            }
          ],
          "description": "The parameter type(s) if any."
        },
        "proposed": {
          "description": "Whether this is a proposed notification. If omitted the notification is final.",
          "type": "boolean"
        },
        "registrationOptions": {
          "$ref": "#/definitions/Type",
          "description": "Optional registration options if the notification supports dynamic registration."
        },
        "since": {
          "description": "Since when (release number) this notification is available. Is undefined if not known.",
          "type": "string"
        }
      },
      "required": ["method"],
      "type": "object"
    },
    "OrType": {
      "additionalProperties": false,
      "description": "Represents an `or` type (e.g. `Location | LocationLink`).",
      "properties": {
        "items": {
          "items": {
            "$ref": "#/definitions/Type"
          },
          "type": "array"
        },
        "kind": {
          "const": "or",
          "type": "string"
        }
      },
      "required": ["kind", "items"],
      "type": "object"
    },
    "Property": {
      "additionalProperties": false,
      "description": "Represents an object property.",
      "properties": {
        "documentation": {
          "description": "An optional documentation.",
          "type": "string"
        },
        "name": {
          "description": "The property name;",
          "type": "string"
        },
        "optional": {
          "description": "Whether the property is optional. If omitted, the property is mandatory.",
          "type": "boolean"
        },
        "proposed": {
          "description": "Whether this is a proposed property. If omitted, the structure is final.",
          "type": "boolean"
        },
        "since": {
          "description": "Since when (release number) this property is available. Is undefined if not known.",
          "type": "string"
        },
        "type": {
          "$ref": "#/definitions/Type",
          "description": "The type of the property"
        }
      },
      "required": ["name", "type"],
      "type": "object"
    },
    "ReferenceType": {
      "additionalProperties": false,
      "description": "Represents a reference to another type (e.g. `TextDocument`). This is either a `Structure`, a `Enumeration` or a `TypeAlias` in the same meta model.",
      "properties": {
        "kind": {
          "const": "reference",
          "type": "string"
        },
        "name": {
          "type": "string"
        }
      },
      "required": ["kind", "name"],
      "type": "object"
    },
    "Request": {
      "additionalProperties": false,
      "description": "Represents a LSP request",
      "properties": {
        "documentation": {
          "description": "An optional documentation;",
          "type": "string"
        },
        "errorData": {
          "$ref": "#/definitions/Type",
          "description": "An optional error data type."
        },
        "method": {
          "description": "The request's method name.",
          "type": "string"
        },
        "params": {
          "anyOf": [
            {
              "$ref": "#/definitions/Type"
            },
            {
              "items": {
                "$ref": "#/definitions/Type"
              },
              "type": "array"
            }
          ],
          "description": "The parameter type(s) if any."
        },
        "partialResult": {
          "$ref": "#/definitions/Type",
          "description": "Optional partial result type if the request supports partial result reporting."
        },
        "proposed": {
          "description": "Whether this is a proposed feature. If omitted the feature is final.",
          "type": "boolean"
        },
        "registrationOptions": {
          "$ref": "#/definitions/Type",
          "description": "Optional registration options if the request supports dynamic registration."
        },
        "result": {
          "$ref": "#/definitions/Type",
          "description": "The result type."
        },
        "since": {
          "description": "Since when (release number) this request is available. Is undefined if not known.",
          "type": "string"
        }
      },
      "required": ["method", "result"],
      "type": "object"
    },
    "StringLiteralType": {
      "additionalProperties": false,
      "description": "Represents a string literal type (e.g. `kind: 'rename'`).",
      "properties": {
        "kind": {
          "const": "stringLiteral",
          "type": "string"
        },
        "value": {
          "type": "string"
        }
      },
      "required": ["kind", "value"],
      "type": "object"
    },
    "Structure": {
      "additionalProperties": false,
      "description": "Defines the structure of an object literal.",
      "properties": {
        "documentation": {
          "description": "An optional documentation;",
          "type": "string"
        },
        "extends": {
          "description": "Structures extended from. This structures form a polymorphic type hierarchy.",
          "items": {
            "$ref": "#/definitions/Type"
          },
          "type": "array"
        },
        "mixins": {
          "description": "Structures to mix in. The properties of these structures are `copied` into this structure. Mixins don't form a polymorphic type hierarchy in LSP.",
          "items": {
            "$ref": "#/definitions/Type"
          },
          "type": "array"
        },
        "name": {
          "description": "The name of the structure.",
          "type": "string"
        },
        "properties": {
          "description": "The properties.",
          "items": {
            "$ref": "#/definitions/Property"
          },
          "type": "array"
        },
        "proposed": {
          "description": "Whether this is a proposed structure. If omitted, the structure is final.",
          "type": "boolean"
        },
        "since": {
          "description": "Since when (release number) this structure is available. Is undefined if not known.",
          "type": "string"
        }
      },
      "required": ["name", "properties"],
      "type": "object"
    },
    "StructureLiteral": {
      "additionalProperties": false,
      "description": "Defines a unnamed structure of an object literal.",
      "properties": {
        "documentation": {
          "description": "An optional documentation.",
          "type": "string"
        },
        "properties": {
          "description": "The properties.",
          "items": {
            "$ref": "#/definitions/Property"
          },
          "type": "array"
        },
        "proposed": {
          "description": "Whether this is a proposed structure. If omitted, the structure is final.",
          "type": "boolean"
        },
        "since": {
          "description": "Since when (release number) this structure is available. Is undefined if not known.",
          "type": "string"
        }
      },
      "required": ["properties"],
      "type": "object"
    },
    "StructureLiteralType": {
      "additionalProperties": false,
      "description": "Represents a literal structure (e.g. `property: { start: uinteger; end: uinteger; }`).",
      "properties": {
        "kind": {
          "const": "literal",
          "type": "string"
        },
        "value": {
          "$ref": "#/definitions/StructureLiteral"
        }
      },
      "required": ["kind", "value"],
      "type": "object"
    },
    "TupleType": {
      "additionalProperties": false,
      "description": "Represents a `tuple` type (e.g. `[integer, integer]`).",
      "properties": {
        "items": {
          "items": {
            "$ref": "#/definitions/Type"
          },
          "type": "array"
        },
        "kind": {
          "const": "tuple",
          "type": "string"
        }
      },
      "required": ["kind", "items"],
      "type": "object"
    },
    "Type": {
      "anyOf": [
        {
          "$ref": "#/definitions/BaseType"
        },
        {
          "$ref": "#/definitions/ReferenceType"
        },
        {
          "$ref": "#/definitions/ArrayType"
        },
        {
          "$ref": "#/definitions/MapType"
        },
        {
          "$ref": "#/definitions/AndType"
        },
        {
          "$ref": "#/definitions/OrType"
        },
        {
          "$ref": "#/definitions/TupleType"
        },
        {
          "$ref": "#/definitions/StructureLiteralType"
        },
        {
          "$ref": "#/definitions/StringLiteralType"
        },
        {
          "$ref": "#/definitions/IntegerLiteralType"
        },
        {
          "$ref": "#/definitions/BooleanLiteralType"
        }
      ]
    },
    "TypeAlias": {
      "additionalProperties": false,
      "description": "Defines a type alias. (e.g. `type Definition = Location | LocationLink`)",
      "properties": {
        "documentation": {
          "description": "An optional documentation.",
          "type": "string"
        },
        "name": {
          "description": "The name of the type alias.",
          "type": "string"
        },
        "proposed": {
          "description": "Whether this is a proposed type alias. If omitted, the type alias is final.",
          "type": "boolean"
        },
        "since": {
          "description": "Since when (release number) this structure is available. Is undefined if not known.",
          "type": "string"
        },
        "type": {
          "$ref": "#/definitions/Type",
          "description": "The aliased type."
        }
      },
      "required": ["name", "type"],
      "type": "object"
    },
    "TypeKind": {
      "enum": [
        "base",
        "reference",
        "array",
        "map",
        "and",
        "or",
        "tuple",
        "literal",
        "stringLiteral",
        "integerLiteral",
        "booleanLiteral"
      ],
      "type": "string"
    }
  }
}
```

Trying to decode the contents of the JSON into a `Schema` fails with:

```
error] java.lang.IllegalStateException: expected preceding call of 'setMark()'
[error]         at com.github.plokhotnyuk.jsoniter_scala.core.JsonReader.missingSetMarkOperation(JsonReader.scala:826)
[error]         at com.github.plokhotnyuk.jsoniter_scala.core.JsonReader.rollbackToMark(JsonReader.scala:74)
[error]         at smithy4s.http.json.SchematicJCodec$$anon$20.decodeValue(SchematicJCodec.scala:565)
[error]         at smithy4s.http.json.SchematicJCodec$$anon$17.decodeValue(SchematicJCodec.scala:453)
[error]         at smithy4s.http.json.Cursor.decode(Cursor.scala:31)
[error]         at smithy4s.http.json.SchematicJCodec$$anon$16.$anonfun$decodeValue$2(SchematicJCodec.scala:393)
[error]         at smithy4s.http.json.Cursor.under(Cursor.scala:37)
[error]         at smithy4s.http.json.Cursor.under(Cursor.scala:45)
[error]         at smithy4s.http.json.SchematicJCodec$$anon$16.decodeValue(SchematicJCodec.scala:393)
[error]         at smithy4s.http.json.SchematicJCodec$$anon$16.decodeValue(SchematicJCodec.scala:374)
[error]         at smithy4s.http.json.Cursor.decode(Cursor.scala:31)
[error]         at smithy4s.http.json.SchematicJCodec.$anonfun$fieldHandler$4(SchematicJCodec.scala:737)
[error]         at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
[error]         at smithy4s.http.json.Cursor.under(Cursor.scala:37)
[error]         at smithy4s.http.json.Cursor.under(Cursor.scala:43)
[error]         at smithy4s.http.json.SchematicJCodec.$anonfun$fieldHandler$3(SchematicJCodec.scala:733)
[error]         at smithy4s.http.json.SchematicJCodec.$anonfun$fieldHandler$3$adapted(SchematicJCodec.scala:731)
[error]         at smithy4s.http.json.SchematicJCodec$$anon$26.decodeValue_(SchematicJCodec.scala:822)
[error]         at smithy4s.http.json.SchematicJCodec$$anon$26.decodeValue(SchematicJCodec.scala:803)
[error]         at smithy4s.http.json.SchematicJCodec$$anon$17.decodeValue(SchematicJCodec.scala:453)
[error]         at smithy4s.http.json.JCodec.$anonfun$decodeMessage$1(JCodec.scala:68)
[error]         at smithy4s.http.json.Cursor$.withCursor(Cursor.scala:75)
[error]         at smithy4s.http.json.JCodec.decodeMessage(JCodec.scala:67)
[error]         at smithy4s.http.json.JCodec.decodeMessage$(JCodec.scala:66)
[error]         at smithy4s.http.json.SchematicJCodec$$anon$17.decodeMessage(SchematicJCodec.scala:447)
[error]         at smithy4s.http.json.JCodec$$anon$1.decodeValue(JCodec.scala:57)
[error]         at smithy4s.http.json.JCodec$$anon$1.decodeValue(JCodec.scala:52)
[error]         at com.github.plokhotnyuk.jsoniter_scala.core.JsonReader.read(JsonReader.scala:580)
[error]         at com.github.plokhotnyuk.jsoniter_scala.core.package$.readFromArray(package.scala:99)
[error]         at smithy4s.http.json.JsonCodecAPI.decodeFromByteArrayPartial(JsonCodecAPI.scala:50)
[error]         at smithy4s.http.json.JsonCodecAPI.decodeFromByteArrayPartial(JsonCodecAPI.scala:28)
[error]         at smithy4s.http.CodecAPI.decodeFromByteArray(CodecAPI.scala:62)
[error]         at smithy4s.http.CodecAPI.decodeFromByteArray$(CodecAPI.scala:58)
[error]         at smithy4s.http.json.JsonCodecAPI.decodeFromByteArray(JsonCodecAPI.scala:28)
[error]         at playground.cli.WIP$.exec(WIP.scala:16)
[error]         at playground.cli.WIP$.delayedEndpoint$playground$cli$WIP$1(WIP.scala:22)
[error]         at playground.cli.WIP$delayedInit$body.apply(WIP.scala)
[error]         at scala.Function0.apply$mcV$sp(Function0.scala:39)
[error]         at scala.Function0.apply$mcV$sp$(Function0.scala:39)
[error]         at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:17)
[error]         at scala.App.$anonfun$main$1(App.scala:76)
[error]         at scala.App.$anonfun$main$1$adapted(App.scala:76)
[error]         at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:563)
[error]         at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:561)
[error]         at scala.collection.AbstractIterable.foreach(Iterable.scala:926)
[error]         at scala.App.main(App.scala:76)
```

**Comment by kubukoz** [comment]
I believe this has something to do with recursion in the schema, potentially within the `Property` type.

**Comment by plokhotnyuk** [comment]
Currently, `setMark()/rollbackToMark()` cannot be called recursively, because jsoniter-scala holds only one mark index. Usually they are used for scanning for some hint keys before main parsing in codecs derived by macros or for detection of numeric value types for schema less codecs.

**Comment by Baccata** [comment]
> Currently, setMark()/rollbackToMark() cannot be called recursively, 

yeah I hadn't foreseen the usage of untagged unions (which requires marking/rollback) with recursive definitions. Is there any existing primitive that could be leveraged to handle the marking on our side ? (I presume it's not the case as it would potentially be unsafe with regards to the reader's state machine)

**Comment by plokhotnyuk** [comment]
> > Currently, setMark()/rollbackToMark() cannot be called recursively,
> 
> yeah I hadn't foreseen the usage of untagged unions (which requires marking/rollback) with recursive definitions. Is there any existing primitive that could be leveraged to handle the marking on our side ? (I presume it's not the case as it would potentially be unsafe with regards to the reader's state machine)

I can add a pair of methods like `def setAndGetMark(): Int` and `def rollbackToMark(mark: Int)` but it would be to inefficient for recursive usage. That can introduce DoS vulnerability for systems with untrusted input.

**Comment by Baccata** [comment]
For more context, this problem is bound to happen only for unions annotated with the `untagged` trait. This trait is there to offer compatibility with existing APIs and patterns and is something that should be discouraged for new APIs. Tagged unions are default in smithy and have my preference because of how they don't require rollback during parsing. 

Say you have this smithy union : 

```
@untagged 
union IntOrString {
  int: Integer, 
  string: String 
}
```

The expected json would look like this, as indicated by the presence of `untagged` : 

* `123`
* "foo"

In other words, `untagged` indicates that there is strictly no way of discriminating between the `Integer` and `String` shapes ahead of time. Therefore, the only way I'm aware of to generically process an untagged union is to attempt parsing against the first member (here Integer), and if that fails, rollback and attempt parsing against the second member (String). 

This is certainly not great, but due to the existence of APIs that use this pattern, supporting it is somewhat required. 
Now the problem is : how do we make it work with recursive unions ? Disregard the unrealism of the following example, but  something like this : 

``` 
structure IntCell {
   @required 
   head: Int, 
   @required
   tail: IntList 
}

@untagged 
untagged IntList {
   some: IntCell 
   none: Unit 
} 
```

valid json payloads for this definition would look like : 

``` 
{ "head" : 1, "tail": { "head" : 2, "tail" : {}} 
```

So what I think is this : if jsoniter can expose a mechanism to support several marks, then that's cool and we use it to fix the bug. **BUT** we add a warning in smithy4s to warn the user against using `untagged` with recursive unions. 

If you can think of a way to support this kind of case generically without using marks/rollbacks, I'm also interested 😄

**Comment by kubukoz** [comment]
> @kubukoz, regardless of the issue (which is very much a bug), why are you using untagged here ? It feels like you should be using discriminated

@Baccata you don't wanna know :joy:

**Comment by kubukoz** [comment]
Rephrased the title - the same issue is now bound to happen if users start using tagged OR discriminated open unions, as per #1677.

So, these combinations:

- tagged (default) with a `@jsonUnknown` member
- `@discriminated` with a `@jsonUnknown` member
- `@untagged`

will be prone to failure if we don't have the ability to do multiple marks in jsoniter.

As far as I can tell, all our marks are used locally, so we don't need Jsoniter to track them - an API like

```scala
getPosition(): Int
rollbackTo(position: Int): Unit
```

should be sufficient. @plokhotnyuk @Baccata thoughts?

**Comment by kubukoz** [comment]
self-correction, I think open unions are actually safe, because we use the mark in a way more similar to discriminated unions' existing marker usage, than untagged ones...

so only untagged unions are the issue - as always.

**Comment by kubukoz** [comment]
I think I'm gonna want this - protocols like LSP rely on untagged unions a bit too much for comfort [with the current limitations]. Both bounded nesting and unbounded recursion will cause trouble.

@plokhotnyuk would you still be open to adding these? https://github.com/disneystreaming/smithy4s/issues/222#issuecomment-1142106022
