### ISSUE TITLE
dump-model & AWS regression in 0.13.0

### ISSUE THREAD

**Issue by kubukoz** [disneystreaming/smithy4s#242]
```
cs launch com.disneystreaming.smithy4s:smithy4s-codegen-cli_2.13:0.13.2 -- dump-model /Users/kubukoz/dev/strum/src/main/smithy/kinesis.json
software.amazon.smithy.model.validation.ValidatedResultException: Result contained ERROR severity validation events: 
[ERROR] com.amazonaws.kinesis#DescribeStream: Unable to resolve trait `smithy.waiters#waitable`. If this is a custom trait, then it must be defined before it can be used in a model. | Model /Users/kubukoz/dev/strum/src/main/smithy/kinesis.json:508:36
[ERROR] com.amazonaws.kinesis#Kinesis_20131202: Unable to resolve trait `aws.api#service`. If this is a custom trait, then it must be defined before it can be used in a model. | Model /Users/kubukoz/dev/strum/src/main/smithy/kinesis.json:1270:28
[ERROR] com.amazonaws.kinesis#Kinesis_20131202: Unable to resolve trait `aws.auth#sigv4`. If this is a custom trait, then it must be defined before it can be used in a model. | Model /Users/kubukoz/dev/strum/src/main/smithy/kinesis.json:1277:27
[ERROR] com.amazonaws.kinesis#Kinesis_20131202: Unable to resolve trait `aws.protocols#awsJson1_1`. If this is a custom trait, then it must be defined before it can be used in a model. | Model /Users/kubukoz/dev/strum/src/main/smithy/kinesis.json:1280:37
        at software.amazon.smithy.model.validation.ValidatedResult.validate(ValidatedResult.java:145)
        at software.amazon.smithy.model.validation.ValidatedResult.unwrap(ValidatedResult.java:132)
        at smithy4s.codegen.ModelLoader$.load(ModelLoader.scala:83)
        at smithy4s.codegen.cli.DumpModel$.run(DumpModel.scala:30)
        at smithy4s.codegen.cli.Main$.$anonfun$main$1(Main.scala:48)
        at smithy4s.codegen.cli.Main$.$anonfun$main$1$adapted(Main.scala:43)
        at scala.util.Either.map(Either.scala:382)
        at smithy4s.codegen.cli.Main$.main(Main.scala:43)
        at smithy4s.codegen.cli.Main.main(Main.scala)
```

The same thing seems to happen for any 0.13.x release (tried kinesis and dynamodb). 0.12.16 worked fine.

Is this intended? If so, what dependency should I use for the aws base model?

**Comment by daddykotex** [comment]
We definitely worked on how the model is built prior to codegen.

TIL: https://awslabs.github.io/smithy/1.0/spec/waiters.html

Let me look while I check if `software.amazon.smithy:smithy-aws-traits:1.11.0` could do it for you

**Comment by daddykotex** [comment]
All of 
1. `aws.api#service`
2. `aws.auth#sigv4`
3. `aws.protocols#awsJson1_1`
can be found in `software.amazon.smithy:smithy-aws-traits:1.11.0`, but I'm still looking for `waiters`

**Comment by daddykotex** [comment]
Ok, can you try to add these deps to your cli run:

`software.amazon.smithy:smithy-aws-traits:1.21.0` and `software.amazon.smithy:smithy-waiters:1.21.0`

**Comment by daddykotex** [comment]
they might be transitively

**Comment by kubukoz** [comment]
Not sure how:

```
cs fetch software.amazon.smithy:smithy-aws-traits:1.21.0                                                                                                                                                                                                                                                                                                                                                                      ✔ | 13s | 16:51:19
/Users/kubukoz/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/software/amazon/smithy/smithy-aws-traits/1.21.0/smithy-aws-traits-1.21.0.jar
/Users/kubukoz/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/software/amazon/smithy/smithy-model/1.21.0/smithy-model-1.21.0.jar
/Users/kubukoz/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/software/amazon/smithy/smithy-utils/1.21.0/smithy-utils-1.21.0.jar
```

anyway, I'm fine adding `traits` at dump site, smithy-playground can probably just add it preemptively

**Comment by kubukoz** [comment]
soo... should this be considered as "working as designed"?
