### ISSUE TITLE
Codegen: generated patterns don't work on Native

### ISSUE THREAD

**Issue by kubukoz** [disneystreaming/smithy4s#498]
Generating the spec for DynamoDB (in particular, this part):

```json
"com.amazonaws.dynamodb#AutoScalingRoleArn": {
  "type": "string",
  "traits": {
    "smithy.api#length": {
      "min": 1,
      "max": 1600
    },
    "smithy.api#pattern": "^[\\u0020-\\uD7FF\\uE000-\\uFFFD\\uD800\\uDC00-\\uDBFF\\uDFFF\\r\\n\\t]*$"
  }
}
```

results in the following pattern string being generated:

```scala
"^[\\u0020-\\uD7FF\\uE000-\\uFFFD\\uD800\\uDC00-\\uDBFF\\uDFFF\\r\\n\\t]*$"
```

and it's not a valid one on the Native platform:

```
java.util.regex.PatternSyntaxException: Illegal/unsupported escape sequence near index 3
^[\u0020-\uD7FF\uE000-\uFFFD\uD800\uDC00-\uDBFF\uDFFF\r\n\t]*$
   ^
        at java.lang.StackTrace$.currentStackTrace(Unknown Source)
        at java.lang.Throwable.fillInStackTrace(Unknown Source)
        at scala.scalanative.regex.Parser$.invalidEscape$1(Unknown Source)
        at scala.scalanative.regex.Parser$.scala$scalanative$regex$Parser$$$parseEscape(Unknown Source)
        at scala.scalanative.regex.Parser$.scala$scalanative$regex$Parser$$$parseClassChar(Unknown Source)
        at scala.scalanative.regex.Parser.parseClass(Unknown Source)
        at scala.scalanative.regex.Parser.scala$scalanative$regex$Parser$$parseInternal(Unknown Source)
        at scala.scalanative.regex.Parser$.parse(Unknown Source)
        at scala.scalanative.regex.RE2$.compileImpl(Unknown Source)
        at scala.scalanative.regex.Pattern$.compile(Unknown Source)
        at scala.scalanative.regex.Pattern$.compile(Unknown Source)
        at java.util.regex.Pattern$.compile(Unknown Source)
        at java.util.regex.Pattern$.compile(Unknown Source)
        at java.util.regex.Pattern.compile(Unknown Source)
        at scala.collection.StringOps$.r$extension(Unknown Source)
        at smithy4s.RefinementProvider$$anon$2.get(Unknown Source)
        at smithy4s.RefinementProvider$$anon$2.get(Unknown Source)
        at smithy4s.RefinementProvider$SimpleImpl.make(Unknown Source)
        at smithy4s.schema.Schema.validated(Unknown Source)
        at smithy4s.schema.Schema$PrimitiveSchema.validated(Unknown Source)
        at DynamoHello$.<init>(Unknown Source)
        at <none>._SM12DynamoHello$G4load(Unknown Source)
        at DynamoHello.main(Unknown Source)
        at <none>.main(Unknown Source)
```

This can be replicated by trying to compile this:

```scala
object DynamoHello extends App {

  Schema
    .string
    .validated(
      smithy
        .api
        .Pattern("^[\\u0020-\\uD7FF\\uE000-\\uFFFD\\uD800\\uDC00-\\uDBFF\\uDFFF\\r\\n\\t]*$")
    )
}
```

or generating the full DynamoDB spec and trying to build a client.

I wonder if this is something that should be fixed in SN (due to being a change in behavior against the JVM/JS implementations) or whether we can do something magical in the codegen - probably the former, I'm afraid.

[Repro on all platforms](https://github.com/kubukoz/demos/tree/smithy4s-pattern-native)

**Comment by kubukoz** [comment]
Actually, this looks like https://github.com/scala-native/scala-native/issues/2645.

**Comment by armanbilge** [comment]
The discussion there also suggested to use just `\` instead of `\\`. But I haven't tried that.

**Comment by Baccata** [comment]
> The discussion there also suggested to use just \ instead of \\. But I haven't tried that.

If that works on all platforms then let's do that.

**Comment by kubukoz** [comment]
@armanbilge FWIW we're going with a single `\`, it seems to work well cross-platform
